### PR TITLE
main: Exit upon unsuccessful initialization

### LINKED ISSUE #352: lxqt-notificationd  doesn't stop after failed registering
If another daemon is running the terminal informs correctly but the notifications daemon doesn't stop, 
If it's module is started it shows just "running", but in fact it's not.
```

$ dunst &
[1] 100957
stef@archlinux:~$ lxqt-notificationd                                                                                                                             
registerService failed: another service with 'org.freedesktop.Notifications' runs already

```

##### Expected Behavior

If a module doesn't work it should stop, also if there is no crash.

##### Possible Solution

Stop the daemon if it fails to register.

##### Steps to Reproduce (for bugs)

1.  Stop lxqt-notificationd module
2. Start another daemon, dunst, mako
3. Start the module, ti will show no error and "running".

##### System Information

* Distribution & Version: git, all; arch

### PR DESCRIPTION
**Pull request by palinek**
Fixes #352

### CODE REVIEW

**Comment by stefonarch** [comment]
Works, it's crashing now 5 times and the message of disabling appears.
GTM

**Comment by palinek** [comment]
It shouldn't crash. It should just stop/exit.

**Comment by stefonarch** [comment]
In the terminal window it exits, but on the GUI if I start it it flickers in the panel 5 times and then the message appears. It's  the message which in this case isn't appropriate. My comment was about this.

screen_area_lun_16:54:17_

Not sure if it's possible to change that message of module start failing only for this case.

**Review by tsujan — APPROVED** [review]
GTM.

> It shouldn't crash. It should just stop/exit.

It doesn't crash. The user just sees lxqt-session's message box, which tells about a crash.

**Comment by stefonarch** [comment]
As this message now isn't a) always correct and b) was always frightening somehow users  we could change the text to something:

**Module Error**

"LXQt could not load %1 module, it's autostart is disabled until next login"

**Pull request merged**
