### PR TITLE
Qt 5.11 beta: Include QStyle and QStyleOption to fix FTBFS

### PR DESCRIPTION
**Pull request by m4sk1n**

### CODE REVIEW

**Comment by tsujan** [comment]
Do you know which header(s) included them before Qt5.11?

**Comment by m4sk1n** [comment]
@tsujan I don't know…

**Comment by tsujan** [comment]
Qt5.11 [isn't stable yet](http://download.qt.io/official_releases/qt/) and a compilation failure may be just because of that.

**Comment by agaida** [comment]
i would suggest to wait with patches for 5.11 until it is released - bonus points for writing bugs about in their bug tracker :)

**Comment by tsujan** [comment]
This shouldn't do any harm -- I also encountered a similar case outside LXQt and included extra headers -- but it may be better to wait until Qt5.11 gets stable; then, we could know why.

It's possible that the behavior of Qt < 5.11 was wrong but it's also possible that the unstable Qt5.11 shows a weird behavior.

**Comment by agaida** [comment]
refs lxqt/lxqt/issues/1487

**Comment by palinek** [comment]
GTM

**Pull request merged**
