### PR TITLE
A better layout for config dialog

### PR DESCRIPTION
**Pull request by tsujan**
As suggested by @stefonarch.

Closes https://github.com/lxqt/lxqt-notificationd/issues/289

### CODE REVIEW

**Comment by stefonarch** [comment]
Quite the same as my branch ;)
I thought all the files should be renamed too, advancedsettings.* → generalsettings.* and basicsettings.* position.* - it could be confusing later keeping the old names.

**Comment by tsujan** [comment]
> I thought all the files should be renamed too,

The less code change, the safer. What's important is what the user sees.

**Comment by stefonarch** [comment]
Not even some comment for the coders in 2050 ;) ?

**Review by stefonarch — APPROVED** [review]
GTM

**Pull request merged**
