### PR TITLE
Support the action_hints hint and update the Dutch translation

### PR DESCRIPTION
**Pull request by ValentijnvdBeek**
Adds supports for the action_hints hint.

Changes the Dutch translation to fix some minor errors, make the translation uniform (multiple translation of deamon/notification), and updates to be contemporary (i.e. notificatie instead of kennisgeving). 

Also fixes a tiny bug in the `getPixmapFromString` routine where it would always try to fetch images from the local disk since almost anything counts as a valid URL.

### CODE REVIEW

**Comment by agaida** [comment]
whoever is able to review this - please do it :) - @luis-pereira @tsujan @palinel @PCMan

**Comment by ValentijnvdBeek** [comment]
@luis-pereira Changed it and squashed the commit

**Comment by luis-pereira** [comment]
@ValentijnvdBeek Can you make a new PR starting with the current master ? 
The current PR contains changes not related to this issue.
It makes review confusing. It can't be merged into master in the current state.

**Comment by agaida** [comment]
and i wonder if it would be better to split the translation and the functionality changes

**Comment by luis-pereira** [comment]
> and i wonder if it would be better to split the translation and the functionality changes

That's also part of it.

**Comment by ValentijnvdBeek** [comment]
@luis-pereira 
No, will not be doing that. 
This is a standalone pull request without _any_ issue attached to it anyway whatsoever. Since a pull request is defined as being agglomeration of different changes in the form of commits any changes made are by definition related to the pull request. So your critique is a bit nonsensical to be honest. 

@agaida Couldn't you have mentioned that two weeks ago when I first filled this PR since that is literally in the name? Or @luis-pereira have mentioned it last week since it is again in the name?

**Comment by tsujan** [comment]
> So your critique is a bit nonsensical to be honest.

Honestly, very rude! It makes sense for a PR to be about one topic; mixing different topics in the same PR isn't good.

It's usual to rebase or change PRs when devs find problems in them.

**Comment by tsujan** [comment]
@ValentijnvdBeek Developers are real people; they live and their days have only 24 hours They may also have serious life problems sometimes. I'm an LXQt member but it might take more than 16 days for my PRs to be reviewed or merged.

**Comment by ValentijnvdBeek** [comment]
@tsujan As far as I know I am also a real person and my days also have 24 hours or am I wrong there?
That is also what I said since I understand you don't always have the time to do things instantly.

**Comment by luis-pereira** [comment]
> No, will not be doing that.
Nothing I can do about that.

> This is a standalone pull request without any issue attached to it anyway whatsoever. Since a pull 
> request is defined as being agglomeration of different changes in the form of commits any changes made are by definition related to the pull request. So your critique is a bit nonsensical to be honest.

No it's not. Commit 34ee2ff2214095ae762423a40fb8ebcf5a9b1da1 mixes updating translations with other stuff.
I didn't review your code. Tried to compile it and it didn't. Just pointed that. Sorry, but will not spend time before it compiles.
I didn't ignore you. Went on vacation and the supposed to work internet connection, didn't work.

**Comment by tsujan** [comment]
> As far as I know I am also a real person

Yes, of course. But you seem to have emotional demands. Here is not the place for them.

**Comment by ValentijnvdBeek** [comment]
@luis-pereira You didn't point that out, I pointed it out since it is stopped compiling after I merged the master back in to fix a merge conflict. 

I honestly had no idea that there was a separate system for translating things since there aren't any contribution guidelines.

I understand that but you could have mentioned that at the beginning.

**Comment by luis-pereira** [comment]
@ValentijnvdBeek I pointed out here https://github.com/lxqt/lxqt-notificationd/pull/96#pullrequestreview-149897173 

> I honestly had no idea that there was a separate system for translating things since there aren't any contribution guidelines

If there aren't, there's something to improve. Good to know.
The general rule is: one commit should do only one thing.

At that point my review was just make it compile. Reviews are dynamic and staged processes.

**Comment by ValentijnvdBeek** [comment]
@tsujan Pretty rude to insult my character based on the fact that I was slightly angry over how things were communicated. 

@luis-pereira I really don't mean this impolitely but that is not what you said. You said that the pull request should only contain changes pertaining to this issue (which I genuinely don't know what it is) and to change a single line.

I'll try to fix the error, is it the one where it complains about `QString::QString(const char*) being private in this context`?

**Comment by luis-pereira** [comment]
I'm still on vacation. It's possible that I will be another week offline. Not sure.

**Comment by ValentijnvdBeek** [comment]
@luis-pereira No problem, just relax and enjoy your vacation.

**Comment by tsujan** [comment]
> @tsujan Pretty rude to insult my character

NEVER your character but your current behavior. And yes, it was rude -- appropriate to the situation you created.

**Comment by ValentijnvdBeek** [comment]
@tsujan Saying that I have emotional needs is insulting my character but, you know what, no offence taken but let's have this be over now.

**Comment by luis-pereira** [comment]
A PR with clean commits. Each commit doing one thing only.
The current PR already compiles. https://github.com/lxqt/lxqt-notificationd/pull/96/commits/8380a16e0eed383b0ad81447ee54d266d7fccbea

**Pull request closed without merging**
