### PR TITLE
Standardize desktop file

### PR DESCRIPTION
**Pull request by stefonarch**
Related https://github.com/lxqt/lxqt-config/pull/1015
The last one IMO

### CODE REVIEW

**Comment by isf63** [comment]
One last one I think -- pavucontrol-qt has the Comment copied into GenericName. It should have its own GenericName.

**Comment by stefonarch** [comment]
> One last one I think -- pavucontrol-qt has the Comment copied into GenericName. It should have its own GenericName.

Identical text is shown only once, but yes, we could improve it too. Feel free to make PR.

**Comment by stefonarch** [comment]
Btw pavucontrol can't be found by its executable in fancymenu:
https://github.com/lxqt/lxqt-panel/issues/2079

**Comment by stefonarch** [comment]
What about this PR?

**Review by tsujan — APPROVED** [review]
It's good.

**Comment by tsujan** [comment]
Oh, it may be better to change ``Do not disturb`` to 'Do not disturb' before merging (using single quotes instead of back quotes).

**Comment by stefonarch** [comment]
I tested single quotes (also backticks first), no issue.

**Comment by tsujan** [comment]
> I tested single quotes (also backticks first), no issue.

Right. I also tested it before suggesting it, although I didn't know what would happen on Weblate.

**Comment by stefonarch** [comment]
Looks like the existing translations will not be removed, I pushed pavucontrol-qt and noticed that the usual translators got notified. 
https://github.com/lxqt/pavucontrol-qt/pull/279/files

**Pull request merged**
