### PR TITLE
Added new hints names as image_data and image_path are deprecated.

### LINKED ISSUE #133: Spotify Track Notifications Show Wrong Album Artwork
When I play music on Spotify, the first notification will display the correct album artwork, but every song after that will continue to show the album artwork of the first song I listened to. I'm not sure what other information to include, as this feels pretty self explanatory to me. What other information would be good?

I hope this is the right place to create this issue. If not, let me know and I'll make the necessary changes.

I'd like to try my hand at fixing this issue myself, but I have no experience with the lxqt project. Could someone point me in the right direction? I've read through the contributing guide but would appreciate specific guidance on where to dig around to debug this specific issue. Hope that's not too much to ask.

Thanks in advance! Here are some screenshots:

### PR DESCRIPTION
**Pull request by zhrexl**
fixes #133 as spotify only sends the right cover art data as "image-data".

### CODE REVIEW

**Comment by tsujan** [comment]
Good catch!

I have two questions and a small request:

 * I can't test Spotify. I guess you tested it with the patch and it worked fine. Is that right?
 * Are you sure it doesn't affect other notifications?
 * Would you please remove the reference to `issue #133` from the code comment? References to issues should be in PR comments and you've already mentioned the issue in the PR.

BTW, if you want an issue to be closed after your PR is merged — which is a good practice — you'll need to add either "closes" or "fixes" before the issue address in your PR comment, like:

closes https://github.com/lxqt/lxqt-notificationd/issues/133
fixes https://github.com/lxqt/lxqt-notificationd/issues/133

"Fix issue ..." won't work.

**Comment by zhrexl** [comment]
>     * I can't test Spotify. I guess you tested it with the patch and it worked fine. Is that right?

That's right. I've been using it for 4 days now and it works fine. if needed, I can provide the `dbus-monitor` output for inspection to confirm this.

>     * Are you sure it doesn't affect other notifications?

If the notification follows the freedesktop's notification specification ([this](https://specifications.freedesktop.org/notification-spec/latest/ar01s05.html)) It won't be affected and as I didn't remove anything and kept the compatibility with the deprecated hints names it definitely should not affect.

>     * Would you please remove the reference to `issue #133` from the code comment? References to issues should be in PR comments and you've already mentioned the issue in the PR.

Sure thing!

> BTW, if you want an issue to be closed after your PR is merged — which is a good practice — you'll need to add either "closes" or "fixes" before the issue address in your PR comment, like:

Does it work if I edit the comment in this PR now?

I'm new to GitHub and interested in learning, please, let me know if there's anything else :)

**Review by tsujan — APPROVED** [review]
GTM

**Comment by tsujan** [comment]
https://developer.gnome.org/notification-spec/ explicitly tells about "image-data" and "image-path". So, your PR is more important than fixing an issue related to Spotify. Thank you very much! Merging...

**Pull request merged**
